package xrpl

import (
	"context"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/andreimerlescu/concert/internal/x402"
)

// testdata/vectors.json was generated by signing with xrpl.js 4.6.0 and
// running @x402/xrpl 2.27.0's facilitator over each blob with the recorded
// ledger state. The Go port must reach the same verdict and reason.
type vectors struct {
	Cases []struct {
		Name         string            `json:"name"`
		Blob         string            `json:"blob"`
		Requirements x402.Requirements `json:"requirements"`
		State        struct {
			Current        uint32 `json:"current"`
			Sequence       uint32 `json:"sequence"`
			RegularKey     string `json:"regularKey"`
			MasterDisabled bool   `json:"masterDisabled"`
			Simulate       string `json:"simulate"`
			Ticket         bool   `json:"ticket"`
		} `json:"state"`
		Valid  bool   `json:"valid"`
		Reason string `json:"reason"`
		Payer  string `json:"payer"`
		Hash   string `json:"hash"`
	} `json:"cases"`
	Keys []struct {
		Seed, Address, PublicKey string
	} `json:"keys"`
	Messages []struct {
		PublicKey, Address, Message, Signature string
	} `json:"messages"`
	Signing []struct {
		Seed string         `json:"seed"`
		Tx   map[string]any `json:"tx"`
		Blob string         `json:"blob"`
	} `json:"signing"`
}

func load(t *testing.T) vectors {
	t.Helper()
	b, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v vectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

type fakeLedger struct {
	mu          sync.Mutex
	networkID   uint32
	current     uint32
	info        AccountInfo
	ticket      bool
	simulate    string
	submitted   []string
	submitError string
	txAfter     int // Tx reports validated from this lookup on
	txResult    string
	lookups     int
	advance     uint32 // ledgers per LedgerIndex call after submission
	nftPages    [][]NFT
}

func (f *fakeLedger) NetworkID(context.Context) (uint32, error) { return f.networkID, nil }
func (f *fakeLedger) LedgerIndex(context.Context) (uint32, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if len(f.submitted) > 0 {
		f.current += f.advance
	}
	return f.current, nil
}
func (f *fakeLedger) AccountInfo(context.Context, string) (AccountInfo, error) { return f.info, nil }
func (f *fakeLedger) TicketAvailable(context.Context, string, uint32) (bool, error) {
	return f.ticket, nil
}
func (f *fakeLedger) Simulate(context.Context, map[string]any) (string, error) {
	return f.simulate, nil
}
func (f *fakeLedger) Submit(_ context.Context, blob string) (string, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.submitted = append(f.submitted, blob)
	if f.submitError != "" {
		return f.submitError, nil
	}
	return "tesSUCCESS", nil
}
func (f *fakeLedger) Tx(context.Context, string) (TxResult, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.lookups++
	if f.lookups < f.txAfter {
		return TxResult{}, nil
	}
	return TxResult{Found: true, Validated: true, Result: f.txResult}, nil
}
func (f *fakeLedger) AccountNFTs(_ context.Context, _ string, marker any) ([]NFT, any, error) {
	i := 0
	if marker != nil {
		i = marker.(int)
	}
	if i >= len(f.nftPages) {
		return nil, nil, errors.New("bad marker")
	}
	var next any
	if i+1 < len(f.nftPages) {
		next = i + 1
	}
	return f.nftPages[i], next, nil
}
func (f *fakeLedger) Fee(context.Context) (uint64, error) { return 12, nil }

func TestVerifyMatchesReferenceFacilitator(t *testing.T) {
	v := load(t)
	for _, c := range v.Cases {
		l := &fakeLedger{networkID: 1, current: c.State.Current, ticket: c.State.Ticket, simulate: c.State.Simulate,
			info: AccountInfo{Sequence: c.State.Sequence, RegularKey: c.State.RegularKey}}
		if c.State.MasterDisabled {
			l.info.Flags = lsfDisableMaster
		}
		s := &Scheme{Network: "xrpl:1", Ledger: l, MaxFeeDrops: DefaultMaxFeeDrops, pending: map[string]time.Time{}}
		p := x402.Payload{Version: 2, Accepted: c.Requirements, Payload: json.RawMessage(`{"signedTxBlob":"` + c.Blob + `"}`)}
		got := s.Verify(context.Background(), p, c.Requirements)
		if got.Valid != c.Valid || got.Reason != c.Reason {
			t.Errorf("%s: got valid=%v %q, reference valid=%v %q", c.Name, got.Valid, got.Reason, c.Valid, c.Reason)
		}
		if c.Valid && got.Payer != c.Payer {
			t.Errorf("%s: payer %s, reference %s", c.Name, got.Payer, c.Payer)
		}
		if tx, err := Decode(c.Blob); err == nil && tx.Hash() != c.Hash {
			t.Errorf("%s: hash %s, reference %s", c.Name, tx.Hash(), c.Hash)
		}
	}
}

func TestKeysMatchRippleKeypairs(t *testing.T) {
	for _, k := range load(t).Keys {
		key, err := KeyFromSeed(k.Seed)
		if err != nil {
			t.Fatal(err)
		}
		if key.Address != k.Address || !strings.EqualFold(hex.EncodeToString(key.Public), k.PublicKey) {
			t.Errorf("seed %s: %s %X, reference %s %s", k.Seed, key.Address, key.Public, k.Address, k.PublicKey)
		}
	}
}

func TestSignedBlobsMatchXrplJS(t *testing.T) {
	for _, c := range load(t).Signing {
		key, _ := KeyFromSeed(c.Seed)
		dest, _ := DecodeAddress(c.Tx["Destination"].(string))
		num := func(k string) uint32 { return uint32(c.Tx[k].(float64)) }
		drops := func(k string) uint64 { n, _ := strconv.ParseUint(c.Tx[k].(string), 10, 64); return n }
		b := NewPayment().Account("Account", AccountID(key.Public)).Account("Destination", dest).
			Drops("Amount", drops("Amount")).Drops("Fee", drops("Fee")).U32("Sequence", num("Sequence")).
			U32("LastLedgerSequence", num("LastLedgerSequence")).Blob("SigningPubKey", key.Public)
		unsigned := b.Bytes()
		sig := key.Sign(append(append([]byte{}, prefixSign...), unsigned...))
		blob := strings.ToUpper(hex.EncodeToString(b.Blob("TxnSignature", sig).Bytes()))
		if blob != c.Blob {
			t.Errorf("seed %s:\n got %s\nwant %s", c.Seed, blob, c.Blob)
		}
	}
}

func TestMessageSignaturesMatchRippleKeypairs(t *testing.T) {
	for _, m := range load(t).Messages {
		sig, _ := base64.StdEncoding.DecodeString(m.Signature)
		addr, ok := VerifyMessage(m.PublicKey, m.Message, sig)
		if !ok || addr != m.Address {
			t.Errorf("%s: ok=%v addr=%s", m.Address, ok, addr)
		}
		if _, ok := VerifyMessage(m.PublicKey, m.Message+"x", sig); ok {
			t.Error("modified message verified")
		}
	}
}

func TestNonCanonicalEncodingsAreRefused(t *testing.T) {
	v := load(t)
	blob := v.Cases[0].Blob
	if _, err := Decode(blob + "00"); err == nil {
		t.Error("trailing byte accepted")
	}
	// Swap the first two fields (TransactionType, Flags or Sequence).
	tx, _ := Decode(blob)
	a, b := tx.fields[0].raw, tx.fields[1].raw
	swapped := hex.EncodeToString(append(append(append([]byte{}, b...), a...), tx.blob[len(a)+len(b):]...))
	if _, err := Decode(swapped); err == nil {
		t.Error("out-of-order fields accepted")
	}
}

func validCase(t *testing.T) (x402.Payload, x402.Requirements, uint32) {
	v := load(t)
	c := v.Cases[0]
	return x402.Payload{Version: 2, Accepted: c.Requirements, Payload: json.RawMessage(`{"signedTxBlob":"` + c.Blob + `"}`)}, c.Requirements, c.State.Current
}

func TestSettleWaitsForValidatedSuccessAndRefusesDuplicates(t *testing.T) {
	p, r, current := validCase(t)
	l := &fakeLedger{networkID: 1, current: current, simulate: "tesSUCCESS", info: AccountInfo{Sequence: 5}, txAfter: 3, txResult: "tesSUCCESS"}
	s := &Scheme{Network: "xrpl:1", Ledger: l, MaxFeeDrops: DefaultMaxFeeDrops, Poll: time.Millisecond, pending: map[string]time.Time{}}
	res, err := s.Settle(context.Background(), p, r)
	if err != nil || !res.Success || len(l.submitted) != 1 || res.Transaction != load(t).Cases[0].Hash {
		t.Fatalf("%+v %v submitted=%d", res, err, len(l.submitted))
	}
	if res, _ := s.Settle(context.Background(), p, r); res.Success || res.ErrorReason != "duplicate_settlement" {
		t.Fatalf("duplicate: %+v", res)
	}
}

func TestSettleReportsFailureAfterLastLedger(t *testing.T) {
	p, r, current := validCase(t)
	l := &fakeLedger{networkID: 1, current: current, simulate: "tesSUCCESS", info: AccountInfo{Sequence: 5}, txAfter: 1 << 30, advance: 5}
	s := &Scheme{Network: "xrpl:1", Ledger: l, MaxFeeDrops: DefaultMaxFeeDrops, Poll: time.Millisecond, pending: map[string]time.Time{}}
	res, err := s.Settle(context.Background(), p, r)
	if err != nil || res.Success || !strings.Contains(res.ErrorReason, "LastLedgerSequence") {
		t.Fatalf("%+v %v", res, err)
	}
}

func TestVerifyRefusesAnEndpointOnAnotherNetwork(t *testing.T) {
	p, r, current := validCase(t)
	l := &fakeLedger{networkID: 0, current: current, simulate: "tesSUCCESS", info: AccountInfo{Sequence: 5}}
	s := &Scheme{Network: "xrpl:1", Ledger: l, MaxFeeDrops: DefaultMaxFeeDrops, pending: map[string]time.Time{}}
	if s.Verify(context.Background(), p, r).Valid {
		t.Fatal("mainnet endpoint accepted for a testnet offer")
	}
}

func TestNFTOwnershipRequiresAuthorizedKeyAndMatchingToken(t *testing.T) {
	v := load(t)
	issuer := v.Keys[2].Address
	for _, m := range v.Messages {
		sig, _ := base64.StdEncoding.DecodeString(m.Signature)
		l := &fakeLedger{networkID: 1, nftPages: [][]NFT{{{Issuer: issuer, NFTokenTaxon: 1, NFTokenID: "A"}}, {{Issuer: issuer, NFTokenTaxon: 7, NFTokenID: "B"}}}}
		s := &Scheme{Network: "xrpl:1", Ledger: l}
		ctx := context.Background()
		if id, err := s.OwnsNFT(ctx, m.Address, issuer+":7", "", m.PublicKey, m.Message, sig); err != nil || id != "B" {
			t.Errorf("%s: %s %v", m.Address, id, err)
		}
		if _, err := s.OwnsNFT(ctx, m.Address, issuer+":7", "A", m.PublicKey, m.Message, sig); err == nil {
			t.Error("token from another taxon accepted")
		}
		if _, err := s.OwnsNFT(ctx, m.Address, issuer+":7", "", m.PublicKey, m.Message+"x", sig); err == nil {
			t.Error("bad signature accepted")
		}
		l.info.Flags = lsfDisableMaster
		if _, err := s.OwnsNFT(ctx, m.Address, issuer+":7", "", m.PublicKey, m.Message, sig); err == nil {
			t.Error("disabled master key accepted")
		}
		l.info.Flags, l.networkID = 0, 0
		if _, err := s.OwnsNFT(ctx, m.Address, issuer+":7", "", m.PublicKey, m.Message, sig); err == nil {
			t.Error("endpoint on another network accepted")
		}
	}
}

func TestClientPaymentsPassVerification(t *testing.T) {
	merchant, _ := KeyFromSeed("sEdTM1uX8pu2do5XvTnutH6HsouMaM2")
	for _, seed := range []string{"sEdSJHS4oiAdz7w2X2ni1gFiqtbJHqE", "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"} {
		key, err := KeyFromSeed(seed)
		if err != nil {
			t.Fatal(err)
		}
		r := x402.Requirements{Scheme: "exact", Network: "xrpl:1", Amount: "1000", Asset: "XRP", PayTo: merchant.Address, MaxTimeoutSeconds: 60,
			Extra: map[string]any{"areFeesSponsored": false, "invoiceId": "order-7", "destinationTag": float64(42)}}
		l := &fakeLedger{networkID: 1, current: 100, simulate: "tesSUCCESS", info: AccountInfo{Sequence: 9}}
		blob, err := NewPaymentBlob(context.Background(), l, key, r)
		if err != nil {
			t.Fatal(err)
		}
		s := &Scheme{Network: "xrpl:1", Ledger: l, MaxFeeDrops: DefaultMaxFeeDrops, pending: map[string]time.Time{}}
		p := x402.Payload{Version: 2, Accepted: r, Payload: json.RawMessage(`{"signedTxBlob":"` + blob + `"}`)}
		if v := s.Verify(context.Background(), p, r); !v.Valid || v.Payer != key.Address {
			t.Errorf("%s: %+v", seed, v)
		}
		l.networkID = 0
		if _, err := NewPaymentBlob(context.Background(), l, key, r); err == nil {
			t.Error("client signed for an endpoint on another network")
		}
	}
}
