// Regenerates docs/third-party/Dependency-notices.txt from the gateway's
// installed production packages. Run after `cd gateway && npm ci`:
//   node scripts/dependency-notices.mjs
import {readFileSync,readdirSync,writeFileSync,existsSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=join(dirname(fileURLToPath(import.meta.url)),'..');
const gateway=join(root,'gateway');
const lock=JSON.parse(readFileSync(join(gateway,'package-lock.json'),'utf8')).packages;
const seen=new Map();
for(const [path,meta] of Object.entries(lock)){
    if(!path||meta.dev||!existsSync(join(gateway,path)))continue;
    const pkg=JSON.parse(readFileSync(join(gateway,path,'package.json'),'utf8'));
    const key=`${pkg.name} ${pkg.version}`;
    if(!seen.has(key))seen.set(key,{pkg,dir:join(gateway,path)});
}
let out='Notices for the Node packages installed by gateway/package-lock.json (production dependencies).\nGenerated by scripts/dependency-notices.mjs. Each package keeps its own license.\n';
for(const key of [...seen.keys()].sort()){
    const {pkg,dir}=seen.get(key);
    const declared=typeof pkg.license==='string'?pkg.license:pkg.license?.type??'see notice';
    const files=readdirSync(dir).filter(f=>/^(licen[cs]e|copying|notice)/i.test(f)).sort();
    out+=`\n\n${key}\nLicense declaration: ${declared}\n`;
    out+=files.length?files.map(f=>`${f}\n${readFileSync(join(dir,f),'utf8').trimEnd()}\n`).join('\n'):'No license file is included in the published package.\n';
}
writeFileSync(join(root,'docs/third-party/Dependency-notices.txt'),out);
console.log(`${seen.size} packages`);